version: "3"

services:
  shop-admin-back:
    hostname: unicorn-shop-admin-back
    image: unicorn-shop-admin-back
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "4300:4300"
