version: "3"

services:
  mongodb_local_single_replica:
    image: mongo:5.0.4
    container_name: mongodb_local_single_replica
    ports:
      - "27037:27037"
    restart: always
    environment:
      - MONGODB_DATABASE="unicorn"
    volumes:
      - ./docker/volume/mongodb_local:/data/db
    entrypoint: [ "/usr/bin/mongod", "--port", "27037", "--bind_ip_all", "--replSet", "rs0" ]
