version: "3"

services:
  mongodb:
    image: mongo:5.0.4
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGODB_DATABASE="test"
    volumes:
      - ./docker/volume/mongodb:/data/db