version: "3"

services:
  shop-admin-back:
    extends:
      file: ./compose.yaml
      service: shop-admin-back
    env_file:
      - ./.env.local

networks:
  jumpserver:
    external: true
  unicorn:
    external: true
