### Create product
POST http://localhost:4300/product/create
Content-Type: application/json

{
    "name": "John Doe",
    "price": 42
}

### Seed categiries
POST http://localhost:4300/seed/categories

### Seed attributes
POST http://localhost:4300/seed/attributes

### Seed products
POST http://localhost:4300/seed/products
